version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2 

jobs:
  build:
    docker:
      - image: circleci/ruby:2.6.3-stretch-node
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: LS & PWD
          command: |
            ls -a
            pwd
      - run:
          name: Install Bundler & Which Bundler?
          command: |
            gem install bundler -v 2.2.16
            bundle -v
      - run:
          name: Install from Gemfile
          command: bundle install
      - run:
          name: Run unit tests using RSpec
          command: >
            mkdir -p /tmp/tests-rspec-results

            bundle exec rspec \
              --format progress \
              --format RspecJunitFormatter \
              --out /tmp/tests-rspec-results/rspec.xml \
              spec/*
      - store_test_results:
          path: /tmp/tests-rspec-results